"""M7 parser-matrix contracts using generated bytes and temporary files only."""

from __future__ import annotations

from io import BytesIO
from pathlib import Path

import pytest
from zipfile import ZipFile

from tests.M7.real_fixtures import fixture_bytes, write_fixture

from app.parser_matrix import (
    MAX_FILE_BYTES,
    PARSER_SPECS,
    ParsedDocument,
    ParsedUnit,
    ParserErrorCode,
    ParserMatrixError,
    detect_format,
    get_parser_spec,
    parse_document,
    parse_file,
    parser_availability,
)

pytestmark = pytest.mark.m7


def _code(error: pytest.ExceptionInfo[ParserMatrixError]) -> ParserErrorCode:
    return error.value.code


def test_parser_matrix_has_exact_one_approved_parser_per_supported_format() -> None:
    expected = {
        "md": ("markdown-it-py", "4.0.0"),
        "txt": ("cpython-textio", "3.11.9"),
        "pdf": ("pypdf", "6.0.0"),
        "pptx": ("python-pptx", "1.0.2"),
        "docx": ("python-docx", "1.2.0"),
    }

    assert set(PARSER_SPECS) == set(expected)
    for format, (parser_id, version) in expected.items():
        spec = get_parser_spec(f".{format.upper()}")
        assert (spec.parser_id, spec.parser_version) == (parser_id, version)
        assert spec.identity == f"{parser_id}@{version}"

    with pytest.raises(ParserMatrixError) as caught:
        get_parser_spec("epub")
    assert _code(caught) is ParserErrorCode.FORMAT_UNSUPPORTED


def test_parser_availability_requires_the_exact_frozen_dependency_version() -> None:
    # The asserted outcome is deliberately environment-neutral: availability is
    # true only if this installation supplies the frozen exact parser version.
    for format, spec in PARSER_SPECS.items():
        assert isinstance(parser_availability(format), bool)
        if parser_availability(format):
            assert get_parser_spec(format) is spec


def test_format_detection_requires_utf8_for_text_and_container_magic_for_binary() -> None:
    def ooxml_bytes(member: str) -> bytes:
        buffer = BytesIO()
        with ZipFile(buffer, "w") as archive:
            archive.writestr("[Content_Types].xml", "<Types />")
            archive.writestr(member, "<document />")
        return buffer.getvalue()

    assert detect_format("标题\n正文".encode("utf-8"), filename="week.MD") == "md"
    assert detect_format(b"\xff", filename="week.txt") is None
    assert detect_format(b"%PDF-1.7\n", filename="misleading.txt") == "pdf"
    assert detect_format(ooxml_bytes("word/document.xml"), filename="notes.docx") == "docx"
    assert detect_format(ooxml_bytes("ppt/presentation.xml"), filename="notes.pptx") == "pptx"
    assert detect_format(b"plain text", filename="unknown.bin") is None


def test_parse_document_rejects_mismatched_declaration_limits_and_disabled_formats() -> None:
    text = "第一课内容".encode("utf-8")

    with pytest.raises(ParserMatrixError) as mismatch:
        parse_document(text, "txt", filename="lesson.md")
    assert _code(mismatch) is ParserErrorCode.FORMAT_MISMATCH

    with pytest.raises(ParserMatrixError) as disabled:
        parse_document(text, "txt", filename="lesson.txt", enabled_formats=())
    assert _code(disabled) is ParserErrorCode.FORMAT_UNSUPPORTED

    with pytest.raises(ParserMatrixError) as over_limit:
        parse_document(b"abc", "txt", filename="lesson.txt", max_bytes=2)
    assert _code(over_limit) is ParserErrorCode.PARSE_LIMIT_EXCEEDED

    with pytest.raises(ParserMatrixError) as invalid_limit:
        parse_document(text, "txt", filename="lesson.txt", max_bytes=MAX_FILE_BYTES + 1)
    assert _code(invalid_limit) is ParserErrorCode.PARSE_LIMIT_EXCEEDED


def test_parse_document_fails_closed_when_selected_parser_is_not_available() -> None:
    # Under a correctly provisioned environment this continues to exercise the
    # selected parser; under a version mismatch it proves no fallback is used.
    if parser_availability("txt"):
        parsed = parse_document("第一课\r\n内容".encode("utf-8"), "txt", filename="lesson.txt")
        assert parsed.format == "txt"
        assert parsed.units[0].text == "第一课\n内容"
    else:
        with pytest.raises(ParserMatrixError) as caught:
            parse_document("第一课\r\n内容".encode("utf-8"), "txt", filename="lesson.txt")
        assert _code(caught) is ParserErrorCode.PARSER_UNAVAILABLE


def test_parse_file_does_not_expose_host_path_when_reading_fails(tmp_path: Path) -> None:
    private_path = tmp_path / "private-root" / "lesson.txt"

    with pytest.raises(ParserMatrixError) as caught:
        parse_file(private_path)

    assert _code(caught) is ParserErrorCode.PARSE_FAILED
    assert str(private_path) not in str(caught.value)


def test_parsed_document_requires_exact_parser_identity_nonempty_units_and_contiguous_ordinals() -> None:
    spec = get_parser_spec("txt")
    unit = ParsedUnit("document", 0, "内容")
    valid = ParsedDocument("txt", spec.parser_id, spec.parser_version, (unit,))
    assert valid.parser_identity == spec.identity

    with pytest.raises(ParserMatrixError):
        ParsedDocument("txt", "fallback-parser", spec.parser_version, (unit,))
    with pytest.raises(ParserMatrixError):
        ParsedDocument("txt", spec.parser_id, spec.parser_version, ())
    with pytest.raises(ParserMatrixError):
        ParsedDocument(
            "txt",
            spec.parser_id,
            spec.parser_version,
            (ParsedUnit("document", 1, "内容"),),
        )


@pytest.mark.parametrize("format", ["md", "txt", "pdf", "pptx", "docx"])
def test_real_binary_and_markdown_parsers_produce_stable_units(tmp_path: Path, format: str) -> None:
    path = write_fixture(tmp_path, format)
    from_bytes = parse_document(path.read_bytes(), format, filename=path.name)
    from_file = parse_file(path, format)

    assert from_bytes == from_file
    assert from_bytes.parser_identity == f"{get_parser_spec(format).parser_id}@{get_parser_spec(format).parser_version}"
    assert from_bytes.units
    assert [unit.ordinal for unit in from_bytes.units] == list(range(len(from_bytes.units)))
    assert all(unit.text.strip() for unit in from_bytes.units)


def test_real_markdown_parser_preserves_heading_context(tmp_path: Path) -> None:
    path = write_fixture(tmp_path, "md")
    document = parse_file(path)
    assert [unit.unit_kind for unit in document.units] == ["heading", "paragraph", "heading", "paragraph"]
    assert document.units[2].heading_path == ("第一章", "简体/繁體")
    assert "中文" in document.units[1].text


def test_real_pptx_parser_skips_hidden_slides_and_preserves_source_ordinal(tmp_path: Path) -> None:
    document = parse_file(write_fixture(tmp_path, "pptx"))
    assert len(document.units) == 1
    assert document.units[0].unit_kind == "slide"
    assert document.units[0].source_ordinal == 1
    assert "Must not be indexed" not in document.units[0].text


def test_real_docx_parser_emits_heading_boundaries(tmp_path: Path) -> None:
    document = parse_file(write_fixture(tmp_path, "docx"))
    assert [unit.unit_kind for unit in document.units] == ["paragraph", "heading", "paragraph", "heading", "paragraph"]
    assert document.units[1].heading_level == 1
    assert document.units[3].heading_path == ("第一节", "小节")


def test_real_pdf_parser_emits_page_unit(tmp_path: Path) -> None:
    document = parse_file(write_fixture(tmp_path, "pdf"))
    assert len(document.units) == 1
    assert document.units[0].unit_kind == "page"
    assert document.units[0].source_ordinal == 1
    assert "PDF page one" in document.units[0].text


def test_real_parser_rejects_corrupt_container_without_path_leak(tmp_path: Path) -> None:
    path = tmp_path / "private-secret.docx"
    path.write_bytes(b"PK\x03\x04not-a-document")
    with pytest.raises(ParserMatrixError) as error:
        parse_file(path)
    assert _code(error) is ParserErrorCode.FORMAT_MISMATCH
    assert str(path) not in str(error.value)


@pytest.mark.parametrize("format", ["md", "txt", "pdf", "pptx", "docx"])
def test_empty_real_document_fails_closed(tmp_path: Path, format: str) -> None:
    path = tmp_path / f"empty.{format}"
    if format in {"md", "txt"}:
        path.write_bytes(b"")
    elif format == "pdf":
        from pypdf import PdfWriter

        output = BytesIO()
        PdfWriter().write(output)
        path.write_bytes(output.getvalue())
    elif format == "pptx":
        from pptx import Presentation

        output = BytesIO()
        Presentation().save(output)
        path.write_bytes(output.getvalue())
    else:
        from docx import Document

        output = BytesIO()
        Document().save(output)
        path.write_bytes(output.getvalue())

    with pytest.raises(ParserMatrixError) as error:
        parse_file(path, format)
    assert _code(error) is ParserErrorCode.PARSE_FAILED
    assert str(path) not in str(error.value)


def test_invalid_utf8_text_fails_closed_without_content_or_path_leak(tmp_path: Path) -> None:
    path = tmp_path / "private-secret.txt"
    path.write_bytes(b"prefix\xffsuffix")
    with pytest.raises(ParserMatrixError) as error:
        parse_file(path, "txt")
    assert _code(error) is ParserErrorCode.PARSE_FAILED
    assert b"prefix" not in str(error.value).encode()
    assert str(path) not in str(error.value)


def test_binary_magic_and_declared_extension_conflicts_fail_closed(tmp_path: Path) -> None:
    path = tmp_path / "private-secret.pdf"
    path.write_bytes(fixture_bytes("pdf"))
    with pytest.raises(ParserMatrixError) as error:
        parse_file(path, "txt")
    assert _code(error) is ParserErrorCode.FORMAT_MISMATCH
    assert str(path) not in str(error.value)
