import hashlib,json,re,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'docs/plans/references';bad=[]
def ck(s,c,d=''):print(('PASS ' if c else 'FAIL ')+s+((' :: '+d) if not c else ''));bad.append(s) if not c else None
def raw(p):return p.read_bytes()
def load(p):return json.loads(raw(p))
def sha(p):return hashlib.sha256(raw(p)).hexdigest()
def canon(p):return raw(p)==(json.dumps(load(p),ensure_ascii=False,sort_keys=True,separators=(',',':'))+'\n').encode()
base='sa-m8-active-draft011-20260914-940ecec4';pp=R/f'external-artifacts/binding/{base}-parent.json';rp=R/f'external-artifacts/binding/{base}-repository.json';gp=R/'external-gates/p2/p2-m8-active-execution-draft011-940ecec4-r01.json';ip=R/f'external-artifacts/identity/{base}.json';p1=R/'external-gates/p1/p1-m8-active-execution-draft011-940ecec4-r01.json';P=R/'m8-active-execution-protocol-draft-0.11.md';D='92e28958eb3e5d938e8646704fa22a297430bfede3d53f04ba941181c9b8d40d';COMMIT='9e80d7e1275a835cdee9fcf5d927f094e2b7d128'
for p in (pp,rp,gp):ck(p.name+' canonical',canon(p));ck(p.name+' logical name',load(p)['logical_name']==p.relative_to(R).as_posix());ck(p.name+' LF',raw(p).endswith(b'\n') and b'\r' not in raw(p))
pa=load(pp);x=pa['payload'];ck('parent digest',sha(pp)=='3b237c6dfd11fd322b0761ef4b520d7e6d942d3a35ddb0eb41d0a3cec027ff9f');ck('parent schema',pa['schema_id']=='sa.m8.parent-binding.v1');ck('parent components',x['components']==['M8-Parents',base]);ck('parent identity shapes',all(re.fullmatch(r'[0-9a-f]{16}',z['volume_serial']) and re.fullmatch(r'[0-9a-f]{32}',z['file_id']) and re.fullmatch(r'[0-9a-f]{64}',z['acl_sha256']) for z in (x['volume_root'],x['parent'])));ck('parent invariants',x['opened_by']=='NtCreateFile' and x['walk']=='volume-root-component-walk' and x['root_directory_relative'] is True and x['share_mask']=='read-write-delete' and x['no_follow'] is True)
r=load(rp);y=r['payload'];pref={'logical_name':pp.relative_to(R).as_posix(),'schema_id':'sa.m8.parent-binding.v1','sha256':sha(pp)};ck('repository digest',sha(rp)=='91af7708a8d73ffe99e185d1cfec8efba8f09ad04768408f2e3bbfc7785bc602');ck('repository schema',r['schema_id']=='sa.m8.repository-binding.v1');ck('clean frozen commit',y['repository_dirty'] is False and y['repository_commit']==COMMIT and y['oid_algorithm']=='sha1');ck('protocol binding',sha(P)==D and y['reviewed_protocol_sha256']==D);ck('identity ref',y['identity_ref']['sha256']==sha(ip));ck('parent ref',y['experiment_parent_binding']==pref);ck('five purposes',[z['purpose'] for z in y['publication_parent_bindings']]==['package','normal-receipt','nonpublication-receipt','abort-receipt','failure-receipt'] and all(z['binding_ref']==pref for z in y['publication_parent_bindings']))
g=load(gp);z=g['payload'];ck('P2 digest',sha(gp)=='7b5efd98b844559d93f67203ee94906555a60e2cb9296d5ac7e5d8a9e73c66a8');ck('P2 decision',z['gate_id']=='P2' and z['decision']=='AUTHORIZED' and z['allowed_next_action']=='request-p3');ck('P2 mapping',z['actor']=={'name':'justtodo123','role':'owner'} and z['independence']['required'] is False and z['independence']['satisfied'] is False and z['scope']['operations']==['binding']);ck('P1 predecessor',z['predecessors']==[{'expected_decision':'AUTHORIZED','expected_next_action':'request-p2','gate_id':'P1','record_id':load(p1)['payload']['record_id'],'record_sha256':sha(p1)}]);ck('repository ref',z['payload']['binding_ref']=={'logical_name':rp.relative_to(R).as_posix(),'schema_id':'sa.m8.repository-binding.v1','sha256':sha(rp)});ck('P2 commit',z['payload']['repository_commit']==COMMIT and z['payload']['oid_algorithm']=='sha1');ck('no P3',not list((R/'external-gates/p3').glob('*draft011*.json')));ck('commit exists',subprocess.run(['git','cat-file','-e',COMMIT+'^{commit}'],cwd=ROOT).returncode==0);print('ALL PASS' if not bad else f'{len(bad)} FAIL');sys.exit(bool(bad))
