import hashlib,json,re,subprocess,sys
from pathlib import Path
ROOT=Path(r'D:\Git Demo\StudyAssistanceAgent'); R=ROOT/'docs/plans/references'; bad=[]
def ck(s,c,d=''): print(('PASS ' if c else 'FAIL ')+s+((' :: '+d) if not c else '')); bad.append(s) if not c else None
def load(p): return json.loads(p.read_text(encoding='utf8'))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def canon(p): return p.read_bytes()==(json.dumps(load(p),ensure_ascii=False,sort_keys=True,separators=(',',':'))+'\n').encode()
base='sa-m8-active-draft010-20260914-5d10f2a1'; pp=R/f'external-artifacts/binding/{base}-parent.json'; rp=R/f'external-artifacts/binding/{base}-repository.json'; gp=R/'external-gates/p2/p2-m8-active-execution-draft010-5d10f2a1-r01.json'; ip=R/f'external-artifacts/identity/{base}-r02.json'; p1=R/'external-gates/p1/p1-m8-active-execution-active-draft010-5d10f2a1-r02.json'; P=R/'m8-active-execution-protocol-draft-0.10.md'; D=sha(P); COMMIT='9e7e9f795f99ca5bce85b09f80495b0d1db031a9'
for p in (pp,rp,gp): ck(p.name+' canonical',canon(p)); ck(p.name+' logical_name',load(p)['logical_name']==p.relative_to(R).as_posix())
pa=load(pp); x=pa['payload']; ck('parent schema',pa['schema_id']=='sa.m8.parent-binding.v1'); ck('parent exact fields',set(x)=={'volume_root','components','parent','opened_by','walk','root_directory_relative','share_mask','no_follow'}); ck('components exact',x['components']==['M8-Parents',base]); ck('identity shapes',all(re.fullmatch(r'[0-9a-f]{16}',z['volume_serial']) and re.fullmatch(r'[0-9a-f]{32}',z['file_id']) and re.fullmatch(r'[0-9a-f]{64}',z['acl_sha256']) and z['filesystem'] in ('ntfs','refs') for z in (x['volume_root'],x['parent']))); ck('same volume serial',x['volume_root']['volume_serial']==x['parent']['volume_serial']); ck('open invariants',x['opened_by']=='NtCreateFile' and x['walk']=='volume-root-component-walk' and x['root_directory_relative'] is True and x['share_mask']=='read-write-delete' and x['no_follow'] is True)
r=load(rp); y=r['payload']; ck('repository schema',r['schema_id']=='sa.m8.repository-binding.v1'); ck('repository exact fields',set(y)=={'identity_ref','reviewed_protocol_path','reviewed_protocol_sha256','repository_commit','oid_algorithm','repository_dirty','experiment_parent_binding','publication_parent_bindings'}); ck('repository clean frozen commit',y['repository_dirty'] is False and y['repository_commit']==COMMIT and y['oid_algorithm']=='sha1'); ck('protocol current',y['reviewed_protocol_sha256']==D); ck('identity ref exact',y['identity_ref']['sha256']==sha(ip) and y['identity_ref']['logical_name']==ip.relative_to(R).as_posix()); ck('experiment parent ref exact',y['experiment_parent_binding']['sha256']==sha(pp)); pubs=y['publication_parent_bindings']; expected=['package','normal-receipt','nonpublication-receipt','abort-receipt','failure-receipt']; ck('five purposes exact order', [z['purpose'] for z in pubs]==expected); ck('five binding refs exact',all(z['binding_ref']==y['experiment_parent_binding'] for z in pubs))
g=load(gp); z=g['payload']; ck('P2 gate schema',g['schema_id']=='sa.m8.external-gate-record.v1'); ck('P2 AUTHORIZED/request-p3',z['gate_id']=='P2' and z['decision']=='AUTHORIZED' and z['allowed_next_action']=='request-p3'); ck('P2 owner binding-only',z['actor']=={'name':'justtodo123','role':'owner'} and z['scope']['operations']==['binding']); ck('P2 no network/production write',z['scope']['allow_network'] is False and z['scope']['allow_production_write'] is False); ck('P2 predecessor P1 r02',z['predecessors'][0]['record_id']==load(p1)['payload']['record_id'] and z['predecessors'][0]['record_sha256']==sha(p1)); ck('P2 binding ref repository',z['payload']['binding_ref']['sha256']==sha(rp)); ck('P2 commit repeated',z['payload']['repository_commit']==COMMIT and z['payload']['oid_algorithm']=='sha1'); ck('P2 protocol current',z['reviewed_protocol_sha256']==D); ck('P2 read refs unique',len({q['logical_name'] for q in z['scope']['read_refs']})==len(z['scope']['read_refs'])); actual=subprocess.run(['git','rev-parse',COMMIT],cwd=ROOT,capture_output=True,text=True).stdout.strip(); ck('frozen commit exists',actual==COMMIT); ck('frozen commit was clean evidence', 'repository snapshot was clean at commit' in z['reason']); print('ALL PASS' if not bad else f'{len(bad)} FAIL'); sys.exit(bool(bad))
