import copy, hashlib, json, re, sys
from pathlib import Path
from jsonschema import Draft202012Validator
ROOT=Path(__file__).resolve().parents[1]; R=ROOT/'docs/plans/references'; P=R/'m8-minimal-1k-dry-run-protocol-v2.md'; S=R/'schemas/m8-minimal-1k-artifacts-v2.schema.json'; schema=json.loads(S.read_bytes()); validator=Draft202012Validator(schema); bad=[]
def ck(n,v): print(('PASS ' if v else 'FAIL ')+n); bad.append(n) if not v else None
def canon(o): return (json.dumps(o,sort_keys=True,separators=(',',':'))+'\n').encode()
def valid(o): return not list(validator.iter_errors(o))
def ref(o): return {'logical_name':o['logical_name'],'schema_id':o['schema_id'],'sha256':hashlib.sha256(canon(o)).hexdigest()}
def env(exp,role,sid,p): return {'canonicalization_id':'sa-json-c14n-v1','logical_name':f'minimal-1k/{exp}/{role}.json','payload':p,'schema_id':sid,'schema_version':2}
H='0'*64; exp='sa-m8-minimal-1k-v2-example'; actor={'name':'justtodo123','role':'owner'}
identity=env(exp,'identity','sa.m8.minimal.experiment-identity.v2',{'experiment_id':exp,'protocol_sha256':hashlib.sha256(P.read_bytes()).hexdigest(),'repository_commit':'0'*40,'clean_status_sha256':H,'python_version':'3.11.9','seed':20260914,'chunk_count':1000,'dimension':512,'dtype':'float32','normalization':'l2','backends':['sqlite-linear-exact','lancedb-embedded-exact-flat'],'query_counts':{'exact':25,'perturbed':25,'metadata-filter':25,'wrong-owner-no-hit':25},'negative_fixture_count':4,'top_k':[1,3,5],'top_k_set_agreement':1.0,'dependency_versions':{'lancedb':'0.38.0','numpy':'2.4.6','pyarrow':'25.0.1','psutil':'7.2.2'},'network_policy':{'acquisition_allowed':True,'measured_allowed':False},'temporary_root_label':'m8-minimal-1k-temp','evidence_directory_label':'m8-minimal-1k-evidence','observer_config':{'network':'getextendedtcptable-plus-socket-ledger-v1','write':'canonical-containment-inventory-v1','redaction':'utf8-sensitive-pattern-scan-v1'},'generator_algorithm':'sa-m8-synthetic-unit-v2','created_at':'2026-09-14T12:00:00Z','owner_actor':actor,'nonce':H})
member=lambda n,c:{'logical_name':f'input/{n}','sha256':H,'byte_count':1,'record_count':c}
manifest=env(exp,'input-manifest','sa.m8.minimal.input-manifest.v2',{'experiment_id':exp,'identity_ref':ref(identity),'config_sha256':H,'synthetic_only':True,'generator_algorithm':'sa-m8-synthetic-unit-v2','chunks':member('chunks.jsonl',1000),'vectors':member('vectors.bin',1000),'queries':member('queries.jsonl',104),'gold':member('gold.jsonl',104)})
metric={'build_ns':1,'query_ns':1,'reopen_ns':1,'peak_rss_bytes':1,'index_bytes':1}; digs={x:H for x in ['exact','perturbed','metadata-filter','wrong-owner-no-hit','negative-fixtures']}
def br(b,m): return {'backend':b,'input_manifest_sha256':ref(manifest)['sha256'],'count':1000,'identity_set_sha256':H,'result_digests':digs,'negative_hit_count':0,'reopen_equal':True,'mode':m,'metrics':metric}
obs={'status':'PASS','event_count':0,'evidence_digest':H}; versions=identity['payload']['dependency_versions']
run=env(exp,'run-report','sa.m8.minimal.run-report.v2',{'experiment_id':exp,'identity_ref':ref(identity),'input_manifest_ref':ref(manifest),'python_version':'3.11.9','dependency_versions':versions,'backends':[br('sqlite-linear-exact','linear-exact'),br('lancedb-embedded-exact-flat','embedded-exact-flat-no-ann')],'network_observer':obs,'write_observer':obs,'redaction_observer':obs,'unexpected_errors':[]})
cleanup=env(exp,'cleanup-receipt','sa.m8.minimal.cleanup-receipt.v2',{'experiment_id':exp,'temporary_root_label':'m8-minimal-1k-temp','evidence_directory_label':'m8-minimal-1k-evidence','before_count':1,'after_count':0,'status':'CLEANED','failure_reason':'none','timestamp':'2026-09-14T12:30:00Z'})
checks=[{'id':f'check-{i:02d}','passed':True,'evidence_digest':H} for i in range(10)]
validation=env(exp,'validation-report','sa.m8.minimal.validation-report.v2',{'experiment_id':exp,'run_report_ref':ref(run),'cleanup_receipt_ref':ref(cleanup),'checks':checks,'verdict':'PASS'})
s2=env(exp,'s2','sa.m8.minimal.decision-record.v2',{'record_id':'s2-example','gate_id':'S2','actor':{'name':'executor-01','role':'executor'},'timestamp':'2026-09-14T12:31:00Z','decision':'EVIDENCE_READY','allowed_next_action':'request-s3','reason':'All checks and cleanup passed.','protocol_sha256':identity['payload']['protocol_sha256'],'experiment_id':exp,'read_refs':[ref(run),ref(validation),ref(cleanup)]})
for n,o in [('identity',identity),('manifest',manifest),('run',run),('cleanup',cleanup),('validation',validation),('s2',s2)]: ck('positive '+n,valid(o) and json.loads(canon(o))==o)
def neg(name,obj,mut): x=copy.deepcopy(obj);mut(x);ck('negative '+name,not valid(x))
neg('10k',identity,lambda x:x['payload'].__setitem__('chunk_count',10000));neg('qdrant',identity,lambda x:x['payload']['backends'].append('qdrant'));neg('network',identity,lambda x:x['payload']['network_policy'].__setitem__('measured_allowed',True));neg('extra field',identity,lambda x:x['payload'].__setitem__('future','x'));neg('missing query counts',identity,lambda x:x['payload'].pop('query_counts'));neg('nonce uppercase',identity,lambda x:x['payload'].__setitem__('nonce','A'*64));neg('backend order',identity,lambda x:x['payload']['backends'].reverse());neg('top k',identity,lambda x:x['payload'].__setitem__('top_k',[1,3,10]));neg('dependency latest',identity,lambda x:x['payload']['dependency_versions'].__setitem__('lancedb','latest'));neg('logical mismatch',identity,lambda x:x.__setitem__('logical_name',f'minimal-1k/{exp}/run-report.json'));neg('run missing backend',run,lambda x:x['payload'].__setitem__('backends',[]));neg('cleanup failure pass validation',cleanup,lambda x:x['payload'].__setitem__('status','FAILED'));neg('unknown actor',s2,lambda x:x['payload']['actor'].__setitem__('role','future-superuser'))
ck('cross same input',run['payload']['backends'][0]['input_manifest_sha256']==run['payload']['backends'][1]['input_manifest_sha256']==ref(manifest)['sha256']);ck('S2 requires cleanup ref',ref(cleanup) in s2['payload']['read_refs'] and validation['payload']['verdict']=='PASS' and cleanup['payload']['status']=='CLEANED');ck('protocol boundaries','不是 draft-0.11 P4' in P.read_text(encoding='utf-8') and '10K 必须另行授权' in P.read_text(encoding='utf-8'));ck('schema canonical',S.read_bytes()==canon(schema));print('ALL PASS' if not bad else f'{len(bad)} FAIL');sys.exit(bool(bad))
